/**
 * Test `descendOnce*` functions.
 */

// This code has been automatically generated by:
// testgen/aas_core_3_0_rc2_typescript_testgen/generate_test_for_descend_once.py
// Do NOT edit or append.

import * as path from "path";
import * as fs from "fs";

import * as AasTypes from "../src/types";
import * as TestCommon from "./common";
import * as TestCommonJsonization from "./commonJsonization";

/**
 * Compare the trace against the golden one from the test data,
 * or re-record the trace if {@link common.RECORD_MODE}.
 *
 * @param instance - to be traced
 * @param expectedPath - path to the golden trace
 */
function compareOrRecordTrace(instance: AasTypes.Class, expectedPath: string) {
  const lines = new Array<string>();
  for (const descendant of instance.descendOnce()) {
    lines.push(TestCommon.traceMark(descendant));
  }
  // NOTE (mristin, 2022-12-09):
  // We add a new line for POSIX systems which prefer a new line
  // at the end of the file.
  lines.push("");
  const got = lines.join("\n");

  if (TestCommon.RECORD_MODE) {
    const parent = path.dirname(expectedPath);
    if (!fs.existsSync(parent)) {
      fs.mkdirSync(parent, { recursive: true });
    }
    fs.writeFileSync(expectedPath, got, "utf-8");
  } else {
    if (!fs.existsSync(expectedPath)) {
      throw new Error(
        `The file with the recorded trace does not exist: ${expectedPath}`
      );
    }

    const expected = fs.readFileSync(expectedPath, "utf-8").replace(/\r\n/g, "\n");
    expect(got).toStrictEqual(expected);
  }
}

test("descendOnce of Extension", () => {
  const instance = TestCommonJsonization.loadCompleteExtension();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "Extension",
      "complete.json.trace"
    )
  );
});

test("descendOnce of AdministrativeInformation", () => {
  const instance = TestCommonJsonization.loadCompleteAdministrativeInformation();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "AdministrativeInformation",
      "complete.json.trace"
    )
  );
});

test("descendOnce of Qualifier", () => {
  const instance = TestCommonJsonization.loadCompleteQualifier();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "Qualifier",
      "complete.json.trace"
    )
  );
});

test("descendOnce of AssetAdministrationShell", () => {
  const instance = TestCommonJsonization.loadCompleteAssetAdministrationShell();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "AssetAdministrationShell",
      "complete.json.trace"
    )
  );
});

test("descendOnce of AssetInformation", () => {
  const instance = TestCommonJsonization.loadCompleteAssetInformation();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "AssetInformation",
      "complete.json.trace"
    )
  );
});

test("descendOnce of Resource", () => {
  const instance = TestCommonJsonization.loadCompleteResource();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "Resource",
      "complete.json.trace"
    )
  );
});

test("descendOnce of SpecificAssetId", () => {
  const instance = TestCommonJsonization.loadCompleteSpecificAssetId();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "SpecificAssetId",
      "complete.json.trace"
    )
  );
});

test("descendOnce of Submodel", () => {
  const instance = TestCommonJsonization.loadCompleteSubmodel();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "Submodel",
      "complete.json.trace"
    )
  );
});

test("descendOnce of RelationshipElement", () => {
  const instance = TestCommonJsonization.loadCompleteRelationshipElement();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "RelationshipElement",
      "complete.json.trace"
    )
  );
});

test("descendOnce of SubmodelElementList", () => {
  const instance = TestCommonJsonization.loadCompleteSubmodelElementList();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "SubmodelElementList",
      "complete.json.trace"
    )
  );
});

test("descendOnce of SubmodelElementCollection", () => {
  const instance = TestCommonJsonization.loadCompleteSubmodelElementCollection();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "SubmodelElementCollection",
      "complete.json.trace"
    )
  );
});

test("descendOnce of Property", () => {
  const instance = TestCommonJsonization.loadCompleteProperty();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "Property",
      "complete.json.trace"
    )
  );
});

test("descendOnce of MultiLanguageProperty", () => {
  const instance = TestCommonJsonization.loadCompleteMultiLanguageProperty();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "MultiLanguageProperty",
      "complete.json.trace"
    )
  );
});

test("descendOnce of Range", () => {
  const instance = TestCommonJsonization.loadCompleteRange();

  compareOrRecordTrace(
    instance,
    path.join(TestCommon.TEST_DATA_DIR, "descendOnce", "Range", "complete.json.trace")
  );
});

test("descendOnce of ReferenceElement", () => {
  const instance = TestCommonJsonization.loadCompleteReferenceElement();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "ReferenceElement",
      "complete.json.trace"
    )
  );
});

test("descendOnce of Blob", () => {
  const instance = TestCommonJsonization.loadCompleteBlob();

  compareOrRecordTrace(
    instance,
    path.join(TestCommon.TEST_DATA_DIR, "descendOnce", "Blob", "complete.json.trace")
  );
});

test("descendOnce of File", () => {
  const instance = TestCommonJsonization.loadCompleteFile();

  compareOrRecordTrace(
    instance,
    path.join(TestCommon.TEST_DATA_DIR, "descendOnce", "File", "complete.json.trace")
  );
});

test("descendOnce of AnnotatedRelationshipElement", () => {
  const instance = TestCommonJsonization.loadCompleteAnnotatedRelationshipElement();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "AnnotatedRelationshipElement",
      "complete.json.trace"
    )
  );
});

test("descendOnce of Entity", () => {
  const instance = TestCommonJsonization.loadCompleteEntity();

  compareOrRecordTrace(
    instance,
    path.join(TestCommon.TEST_DATA_DIR, "descendOnce", "Entity", "complete.json.trace")
  );
});

test("descendOnce of EventPayload", () => {
  const instance = TestCommonJsonization.loadCompleteEventPayload();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "EventPayload",
      "complete.json.trace"
    )
  );
});

test("descendOnce of BasicEventElement", () => {
  const instance = TestCommonJsonization.loadCompleteBasicEventElement();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "BasicEventElement",
      "complete.json.trace"
    )
  );
});

test("descendOnce of Operation", () => {
  const instance = TestCommonJsonization.loadCompleteOperation();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "Operation",
      "complete.json.trace"
    )
  );
});

test("descendOnce of OperationVariable", () => {
  const instance = TestCommonJsonization.loadCompleteOperationVariable();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "OperationVariable",
      "complete.json.trace"
    )
  );
});

test("descendOnce of Capability", () => {
  const instance = TestCommonJsonization.loadCompleteCapability();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "Capability",
      "complete.json.trace"
    )
  );
});

test("descendOnce of ConceptDescription", () => {
  const instance = TestCommonJsonization.loadCompleteConceptDescription();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "ConceptDescription",
      "complete.json.trace"
    )
  );
});

test("descendOnce of Reference", () => {
  const instance = TestCommonJsonization.loadCompleteReference();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "Reference",
      "complete.json.trace"
    )
  );
});

test("descendOnce of Key", () => {
  const instance = TestCommonJsonization.loadCompleteKey();

  compareOrRecordTrace(
    instance,
    path.join(TestCommon.TEST_DATA_DIR, "descendOnce", "Key", "complete.json.trace")
  );
});

test("descendOnce of LangString", () => {
  const instance = TestCommonJsonization.loadCompleteLangString();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "LangString",
      "complete.json.trace"
    )
  );
});

test("descendOnce of Environment", () => {
  const instance = TestCommonJsonization.loadCompleteEnvironment();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "Environment",
      "complete.json.trace"
    )
  );
});

test("descendOnce of EmbeddedDataSpecification", () => {
  const instance = TestCommonJsonization.loadCompleteEmbeddedDataSpecification();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "EmbeddedDataSpecification",
      "complete.json.trace"
    )
  );
});

test("descendOnce of ValueReferencePair", () => {
  const instance = TestCommonJsonization.loadCompleteValueReferencePair();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "ValueReferencePair",
      "complete.json.trace"
    )
  );
});

test("descendOnce of ValueList", () => {
  const instance = TestCommonJsonization.loadCompleteValueList();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "ValueList",
      "complete.json.trace"
    )
  );
});

test("descendOnce of DataSpecificationIec61360", () => {
  const instance = TestCommonJsonization.loadCompleteDataSpecificationIec61360();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "DataSpecificationIEC61360",
      "complete.json.trace"
    )
  );
});

test("descendOnce of DataSpecificationPhysicalUnit", () => {
  const instance = TestCommonJsonization.loadCompleteDataSpecificationPhysicalUnit();

  compareOrRecordTrace(
    instance,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "descendOnce",
      "DataSpecificationPhysicalUnit",
      "complete.json.trace"
    )
  );
});
