/**
 * Test verification functions related to dates.
 *
 * @remark
 * We test only the extras which are not already covered by the test data
 * generated by aas-core3.0rc02-testgen.
 */

import * as AasVerification from "../src/verification";

test("leap years CE", () => {
  expect(AasVerification.isLeapYear(2000)).toBeTruthy();
  expect(AasVerification.isLeapYear(1600)).toBeTruthy();
  expect(AasVerification.isLeapYear(1604)).toBeTruthy();

  expect(AasVerification.isLeapYear(1700)).toBeFalsy();
  expect(AasVerification.isLeapYear(1800)).toBeFalsy();
});

test("leap years BCE", () => {
  expect(AasVerification.isLeapYear(-1)).toBeTruthy();
  expect(AasVerification.isLeapYear(-5)).toBeTruthy();

  expect(AasVerification.isLeapYear(-4)).toBeFalsy();
});
